region="eu-west-1"
aws_profile_name="davesprofile"
aws_creds_file="/root/.aws/credentials"
dockerhub_auth="ZGF2aWRtaXQ6bWl0Y2hlbGw="
dockerhub_email="mail@dave-mitchell.com"
public_key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDYE6KBvxhtAXYcWzbaW+l7mv4jq1h8rZzqyeWmBIKo7eJyrhwDellg6ydhm63GxR/qKqhaDfLeOmxtFg6RCn3dmOIlpaEQK1gOS1qMANaSVuowxpQv+FSm3y01UBHhgmGtLUXOc2fo6oziY0pts9sIeaQ7WeoJDrNj6lz968IqLw=="
key_name="akey"
